#!/usr/bin/env python

import pyexotica._pyexotica as exo
from numpy import array
from pyexotica_modules.publish_trajectory import *

solver = exo.Setup.load_solver(
    '{exotica_examples}/resources/configs/example_ompl.xml')

solution = solver.solve()

plot(solution)
